# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: your_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10your_proto.proto\"\r\n\x0b\x44\x61taRequest\"\x0e\n\x0c\x44\x61taResponse25\n\x0bYourService\x12&\n\x07GetData\x12\x0c.DataRequest\x1a\r.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'your_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=20
  _globals['_DATAREQUEST']._serialized_end=33
  _globals['_DATARESPONSE']._serialized_start=35
  _globals['_DATARESPONSE']._serialized_end=49
  _globals['_YOURSERVICE']._serialized_start=51
  _globals['_YOURSERVICE']._serialized_end=104
# @@protoc_insertion_point(module_scope)
